class Answers:
    default = "Выбери команду из списка кнопок"
    askQuestion = "Задай вопрос и я попробую ответить на него"
    enterText = "Введи текст и я создам по нему изображение"
    waiting = "Думаю..."
    forbiddenText = "Такое я сделать не могу"
    setCreativityAI = "Введи число от 0 до 0.9, где 0 - чётко определённый ответ, 0.9 - креативный ответ"
    setAmountImages = "Введи число от 1 до 10"
    settingsChanged = "Настройки изменены"
    wrongFormat = "Неверный формат"